### PR TITLE
E Business Card

### PR DESCRIPTION
**Pull request by tanishq-mishra**
First Flutter app

### CODE REVIEW

**Comment by rahulkp220** [comment]
Hi Tanishq,
Congratulations 🎉 on your first contribution to the repo. As a next step, can you please update the readme with the screenshot of the new app?

Reg,
Rahul

**Comment by tanishq-mishra** [comment]
Hey Rahul, 
As you've told me, I have added the Screenshot at the bottom of the readme.

Regards, 
Tanishq

**Comment by tanishq-mishra** [comment]
Haven't added the screenshots of the second app (BMI Calculator) though.

**Comment by rahulkp220** [comment]
Hi Tanishq,
Thanks for adding that, however for every new app, it would be great to have a screenshot as well. Once you add that in, I would be happy to merge your PR.

**Comment by tanishq-mishra** [comment]
I've Uploaded the Screenshots for both the apps

**Pull request merged**
